### ISSUE TITLE
disabling Ambient Mode in Fullscreen stops working if YTHoldForSpeed is active

### ISSUE THREAD

**Issue by arichornlover** [joshuaseltzer/YTHoldForSpeed#9]
this is probably one of the dumbest issues I’ve made but was wondering on how to fix this?
in other tweaks, I’ve made an option to Hide Ambient Mode in Fullscreen but for some weird reason, it stops working when YTHoldForSpeed is active? This ain’t caused by YouTube. It’s a custom option I’ve made to remove ambient mode in Fullscreen and you can check the code and the issue below if you want to check it out.
https://github.com/arichorn/uYouEnhanced/issues/271
```
// Disable Ambient Mode in Fullscreen - @arichorn
%hook YTCinematicContainerView
- (BOOL)watchFullScreenCinematicSupported {
    return NO;
}
- (BOOL)watchFullScreenCinematicEnabled {
    return NO;
}
%end
```

**Comment by joshuaseltzer** [comment]
I just checked my code and it doesn't look like any of my code should directly conflict with the hooks for Ambient Mode. Although I'll admit, I don't even know what Ambient Mode is, so it's hard for me to test or know what could potentially be creating this issue.

The only thing I can think of, is that this feature is reliant on a the stock long press gestures that YouTube uses, which I specifically ensure are never created so that my custom gesture (to change the playback speed) is used instead.

**Comment by joshuaseltzer** [comment]
No need to apologize, it very well could be something that this tweak is doing to conflict with that functionality.

If your hooks work without YTHoldForSpeed installed, then there probably is some sort of conflict. I'd guess that it would be casued by the stock gestures I'm forcefully removing to make sure the custom gesture is working. See these hooks for more information: https://github.com/joshuaseltzer/YTHoldForSpeed/blob/main/YTHFSTweak.x#L178
